### ISSUE TITLE
C++ modules via `dlopen`

### ISSUE THREAD

**Issue by KCreate** [KCreate/charly-vm#15]
Allow the loading of modules at runtime using `dlopen`

**Comment by KCreate** [comment]
Module system has been implemented

**Comment by tekknolagi** [comment]
Link to commit/PR?

**Comment by KCreate** [comment]
Everything should be in the following commits, maybe I forgot some...
eff54c9f0eff4f3cbad19542d7daf26fa7041a20
dd2a2ea4a0a90ae612529cbd6c6b9abec3aa8864
5d92124b52bea5313082d4ac4dfc79f543dcf6f4
a1d921ee6069dda98bd7e868f7fea750d3f39547
